services:
  - type: web
    name: task-manager
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "uv run gunicorn task_manager.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: task-manager-db
          property: connectionString

databases:
  - name: task-manager-db
    databaseName: task_manager
    user: task_manager_user